UPDATES

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,12 +1,34 @@
 #!/bin/sh
 
+set -eu
+
 HERE="$(dirname "$(readlink -f "$0")")"
-XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
-PROGRAMSDIR="${PROGRAMSDIR:-$HOME/programs}"
+. "$HERE/.config/shell/env"
+
+SETUP_PROGRAMS_DIR="${SETUP_PROGRAMS_DIR:-$HOME/programs}"
+SETUP_PKGS_FILE="${SETUP_PKGS_FILE:-$XDG_DATA_HOME/PACK/pkglist.txt}"
+SETUP_PKGS_FILE="${SETUP_PKGS_FILE:-$XDG_DATA_HOME/PACK/pkgs_aur.txt}"
+SETUP_PKGS_FILE="${SETUP_PKGS_FILE:-$XDG_DATA_HOME/PACK/flatpak.txt}"
+
+[ -n "${SETUP_BROWSER_DIR:-}" ] || case "$BROWSER" in
+	zen-browser) SETUP_BROWSER_DIR="$HOME/.zen" ;;
+	firefox) SETUP_BROWSER_DIR="$HOME/.mozilla/firefox" ;;
+	*)
+
+		[ "$1" = "browser" ] || [ "$1" = "all" ] && {
+			echo "$(basename "$0"): cannot determine SETUP_BROWSER_DIR" >&2
+			exit 1
+		}
+		;;
+esac
 
 # shellcheck disable=2015
 sudocmd="$([ -s /etc/doas.conf ] && command -v doas 2>/dev/null || command -v sudo 2>/dev/null)"
-browserdir="$HOME/.mozilla/firefox"
+
+[ "$(id -u)" -eq 0 ] && {
+	echo "$(basename "$0"): this script should not run as root" >&2
+	exit 1
+}
 
 setup_dotfiles() {
 	cp -srvft "$HOME" "$HERE/.config" "$HERE/.local"
@@ -16,6 +38,39 @@ setup_dotfiles() {
 	$sudocmd cp -rvft /etc/pacman.d "$HERE/.config/pacman/hooks"
 	$sudocmd mkdir -p /var/cache/zsh
 }
+
+setup_pkgs() {
+	$sudocmd pacman -Syu --noconfirm
+	$sudocmd pacman -S --needed --noconfirm artix-archlinux-support &&
+		$sudocmd pacman-key --populate archlinux &&
+		$sudocmd pacman -Sy --noconfirm
+	[ -r "$SETUP_PKGS_FILE" ] &&
+		$sudocmd pacman -S --needed --noconfirm - <"$SETUP_PKGS_FILE"
+	[ -r "$SETUP_PKGS_AUR_FILE" ] && {
+		command -v paru >/dev/null 2>&1 || {
+			git clone https://aur.archlinux.org/paru.git "$SETUP_PROGRAMS_DIR/paru" &&
+				makepkg -siD "$SETUP_PROGRAMS_DIR/paru"
+		}
+		paru -Sa --needed --noconfirm --sudo "$sudocmd" - <"$SETUP_PKGS_AUR_FILE"
+	}
+	command -v go >/dev/null 2>&1 &&
+		go telemetry off
+	command -v rustup >/dev/null 2>&1 &&
+		rustup default stable &&
+		cargo install cargo-update cargo-info
+	command -v wine >/dev/null 2>&1 &&
+		mkdir -pv "$WINEPREFIX"
+	[ -r "$SETUP_PKGS_FLATPAKS_FILE" ] &&
+		command -v flatpak >/dev/null 2>&1 &&
+		xargs flatpak install -y <"$SETUP_PKGS_FLATPAKS_FILE"
+}
+
+setup_user() {
+	chsh -s "$(which zsh)"
+	$sudocmd ln -svfT dash /usr/bin/sh
+	$sudocmd usermod -aG video,audio,input,power,storage,optical,network,lp,scanner,dbus,realtime,docker,nix-users,nixbld,adbusers,uucp,informant "$USER"
+}
+
 
 setup_runit() {
 	doas rm -vf \
@@ -37,34 +92,89 @@ setup_runit() {
 		/etc/runit/sv/docker
 }
 
-setup_firefox() {
-	[ -d "$browserdir" ] ||
-		{ firefox --headless >/dev/null 2>&1 & ffpid=$!; sleep 1; }
-	profile="$(sed -n "/Default=.*\..*/s/.*=//p" "$browserdir/profiles.ini")"
-	cat "/usr/share/arkenfox-user.js/user.js" "$XDG_CONFIG_HOME/firefox/user.js" >"$browserdir/$profile/user.js"
-	# shellcheck disable=SC2015
-	[ -n "$ffpid" ] && kill "$ffpid" || true
+setup_fonts() {
+	$sudocmd ln -svft /etc/fonts/conf.d/ /usr/share/fontconfig/conf.avail/10-nerd-font-symbols.conf
 }
 
-clean() {
-	cd "$HERE" || exit 1
-	find .config .local -type f -exec rm -vf "$HOME/{}" \;
-	profile="$(sed -n "/Default=.*\..*/s/.*=//p" "$browserdir/profiles.ini")"
-	[ -s "$browserdir/$profile/user.js" ] && rm -vf "$browserdir/$profile/user.js"
+setup_pipewire() {
+	$sudocmd cp -afvt /etc /usr/share/pipewire /usr/share/wireplumber
 }
 
-case "$1" in
-	""|all)
-		setup_dotfiles
-		setup_runit
-		setup_firefox
-		;;
+setup_ufw() {
+	$sudocmd ufw default deny
+	$sudocmd ufw allow from 192.168.0.0/24
+	$sudocmd ufw limit ssh
+}
+
+
+setup_browser() {
+	[ -d "$SETUP_BROWSER_DIR" ] || {
+		$BROWSER --headless >/dev/null 2>&1 &
+		ffpid=$!
+		sleep 1
+	}
+	sed -n "/Default=.*\..*/s/.*=//p" "$SETUP_BROWSER_DIR/profiles.ini" |
+		while IFS= read -r p; do
+			cat "/usr/share/arkenfox-user.js/user.js" >"$SETUP_BROWSER_DIR/$p/user.js"
+			browsers="firefox"
+			# shellcheck disable=2015
+			[ "$BROWSER" != "$browsers" ] && browsers="$browsers $BROWSER" || true
+			for b in $browsers; do
+				[ -r "$XDG_CONFIG_HOME/$b/user.js" ] &&
+					cat "$XDG_CONFIG_HOME/$b/user.js" >>"$SETUP_BROWSER_DIR/$p/user.js"
+				[ -d "$XDG_CONFIG_HOME/$b/chrome" ] &&
+					cp -rvL "$XDG_CONFIG_HOME/$b/chrome" "$SETUP_BROWSER_DIR/$p"
+			done
+		done
+	# shellcheck disable=2015
+	[ -n "${ffpid:-}" ] && kill "$ffpid" || true
+}
+
+setup_install() {
+	setup_dotfiles
+	setup_pkgs
+	setup_user
+	setup_runit
+	setup_ufw
+	setup_fonts
+	setup_pipewire
+	setup_browser
+}
+
+setup_uninstall() {
+	find "$HERE/.config" "$HERE/.local" -type f |
+		while IFS= read -r p; do
+			f="${p#"$HERE/"}"
+			# shellcheck disable=2015
+			[ -L "$HOME/$f" ] &&
+				[ "$HERE/$f" = "$(readlink -f "$HOME/$f")" ] ||
+				continue
+			rm -vf "$HOME/$f"
+		done
+	sed -n "/Default=.*\..*/s/.*=//p" "$SETUP_BROWSER_DIR/profiles.ini" |
+		while IFS= read -r p; do
+			# shellcheck disable=2015
+			[ -r "$SETUP_BROWSER_DIR/$p/user.js" ] &&
+				cat "/usr/share/arkenfox-user.js/user.js" "$XDG_CONFIG_HOME/firefox/user.js" "$XDG_CONFIG_HOME/$BROWSER/user.js" |
+				cmp "$SETUP_BROWSER_DIR/$p/user.js" ||
+				continue
+			rm -vf "$SETUP_BROWSER_DIR/$p/user.js"
+		done
+}
+
+case "${1:-dotfiles}" in
+	install) setup_install ;;
 	dotfiles) setup_dotfiles ;;
+	pkgs) setup_pkgs ;;
+	user) setup_user ;;
 	runit) setup_runit ;;
-	firefox) setup_firefox ;;
-	clean) clean ;;
+	ufw) setup_ufw ;;
+	fonts) setup_fonts ;;
+	pipewire) setup_pipewire ;;
+	browser) setup_browser ;;
+	uninstall) setup_uninstall ;;
 	*)
-		echo "$(basename "$0"): unknown command \"$1\"" >&2
+		echo "$(basename "$0"): unknown command: $1" >&2
 		exit 1
 		;;
 esac
